In [ ]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [ ]:
churn = pd.read_csv("fun.csv")
churn.head()

DATE   1   2   3   4   5   6   7   8
0  2022-08-09  16  19  25  26  27  33  45  38
1  2022-08-05   7  16  19  33  36  48  49   5
2  2022-08-02   4   5  15  18  22  28  32  19
3  2022-07-29   7  14  17  18  19  23  41  16
4  2022-07-26   3   8   9  15  21  27  31  33

In [ ]:
churn['8'] = churn['8'].astype("int")
churn.head()

DATE   1   2   3   4   5   6   7   8
0  2022-08-09  16  19  25  26  27  33  45  38
1  2022-08-05   7  16  19  33  36  48  49   5
2  2022-08-02   4   5  15  18  22  28  32  19
3  2022-07-29   7  14  17  18  19  23  41  16
4  2022-07-26   3   8   9  15  21  27  31  33

In [ ]:
x = np.asarray(churn[['1', '2', '3', '4', '5', '6', '7', '8']])
x[0:5]

array([[16, 19, 25, 26, 27, 33, 45, 38],
       [ 7, 16, 19, 33, 36, 48, 49,  5],
       [ 4,  5, 15, 18, 22, 28, 32, 19],
       [ 7, 14, 17, 18, 19, 23, 41, 16],
       [ 3,  8,  9, 15, 21, 27, 31, 33]])

In [ ]:
y = np.asarray(churn['8'])
y

array([38,  5, 19, 16, 33,  6,  4, 48, 37, 19, 13, 50, 10, 28, 43, 38, 34,
       23, 31, 42, 37,  5, 22, 14, 23, 30, 24, 26, 31, 45, 22, 33, 43, 35,
       25,  4, 20, 41, 42, 17,  1, 25, 27,  1, 39, 23, 27,  5, 50, 36,  6,
        4, 18,  1, 42, 16, 37, 41, 31, 26, 12, 11, 36])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2, random_state = 4)
print(xtrain.shape, ytrain.shape)
print(xtest.shape, ytest.shape)

(50, 8) (50,)
(13, 8) (13,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C = 0.01, solver="liblinear").fit(xtrain, ytrain)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(xtest)
yhat

array([50, 42, 36, 18, 42, 36, 36, 43, 31, 13,  1, 42, 50])

In [ ]:
yhat_prob = LR.predict_proba(xtest)
yhat_prob

array([[1.81777977e-03, 6.02562206e-03, 4.76525411e-03, 3.90531400e-03,
        7.40978050e-03, 5.85195789e-03, 8.05329727e-03, 5.26617188e-03,
        1.21195440e-02, 2.10631619e-02, 1.64898541e-02, 7.59123139e-03,
        3.24682757e-02, 9.59100388e-03, 2.29247776e-02, 3.78893597e-02,
        2.00582394e-02, 2.65944217e-02, 4.25880611e-02, 2.11080181e-02,
        6.27732550e-02, 3.39718022e-02, 3.89231970e-02, 5.16735252e-02,
        6.60026914e-02, 7.16722614e-02, 2.52996832e-02, 7.54651770e-02,
        1.00517571e-01, 5.90724944e-02, 1.01047216e-01],
       [3.04085092e-03, 8.39857662e-03, 1.08754075e-02, 2.02823311e-02,
        1.91652903e-02, 1.70063373e-02, 9.00247694e-03, 1.94308769e-02,
        1.65325850e-02, 1.18492573e-02, 1.39560426e-02, 3.01189462e-02,
        3.18590710e-02, 3.79844363e-02, 2.44027129e-02, 3.19104388e-02,
        2.40558219e-02, 9.72718066e-03, 4.68196563e-02, 8.72174380e-03,
        1.12620452e-01, 3.50161063e-02, 2.30728769e-02, 1.06120264e-02,
       