In [7]:
import numpy as np
from scipy import sparse

In [2]:
# 1.1
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1], [2], [3]])

print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [6]:
# 1.2 create a matrix
matrix_object = np.asmatrix([[1, 2], 
                   [3, 4], 
                   [5, 6]])
print(matrix_object)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
# 1.3 creating a sparse matrix
matrix = np.array([[0, 7], 
                  [0, 1], 
                  [3, 0]])
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 2)>
  Coords	Values
  (0, 1)	7
  (1, 1)	1
  (2, 0)	3


In [11]:
matrix_large = np.array([[0, 0, 0, 0, 0], 
                         [0, 1, 0, 0, 4], 
                         [3, 0, 0, 5, 1]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 5)>
  Coords	Values
  (1, 1)	1
  (1, 4)	4
  (2, 0)	3
  (2, 3)	5
  (2, 4)	1


In [17]:
# 1.4 selecting elements
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(matrix[0, 1])
print(vector[0:3])
print(matrix[1:3, 0:2])

2
[1 2 3]
[[4 5]
 [7 8]]


In [20]:
# 1.5 describing a matrix
matrix = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)


(3, 4)
12
2


In [22]:
#1.6 Applying operations to elements
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

add_100 = lambda i: i + 100
vectorized_add_100 = np.vectorize(add_100)
print(vectorized_add_100(matrix))

[[101 102 103]
 [104 105 106]
 [107 108 109]]


In [30]:
# 1.7 finding the maximu and minimum values

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(np.max(matrix, axis=0))
print(np.min(matrix, axis=1))

[7 8 9]
[1 4 7]


In [35]:
# 1.8 calculate the average, variance, and standard deviation
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print("mean: ", np.mean(matrix, axis=0))
print("var: ", np.var(matrix))
print("std: ", np.std(matrix, axis=0))

mean:  [4. 5. 6.]
var:  6.666666666666667
std:  [2.44948974 2.44948974 2.44948974]


In [37]:
# 1.9 reshaping arrays
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9], 
                   [10, 11, 12]])
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
# 1.10 transposing a vector or matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(matrix.T)
# a vector cannot be transposed because it is just a collection of values
# but a row vector can be transposed to a column vector

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [39]:
# 1.11 flattening a matrix
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(matrix.flatten())


[1 2 3 4 5 6 7 8 9]


In [43]:
# 1.12 finding the rank of a matrix 
matrix = np.array([[1, 1, 3], 
                   [1, 1, 10], 
                   [1, 1, 15]])
np.linalg.matrix_rank(matrix)
# rank of a matrix is the dimenison of the vector space spanned by its columns or rows

np.int64(2)

In [44]:
# 1.13 calculating the determinant
matrix = np.array([[1, 2, 3], 
                   [2, 4, 6], 
                   [3, 8, 9]])
np.linalg.det(matrix)

np.float64(0.0)

In [45]:
# 1.14 getting the diagonal of a matrix
matrix = np.array ([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(matrix.diagonal())



[1 5 9]


In [46]:
# 1.15 calculating the tract of a matrix 
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(np.trace(matrix))
# tract is the sum of the diagonal elements of a square matrix

15


In [48]:
# 1.16 finding eigenvalues and eignevectors 
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# eigenvalues are the values that, when multiplied by the eigenvectors, give the original matrix
# eigenvectors are the vectors that, when multiplied by the eigenvalues, give the original matrix
eignevalues, eigenvectors = np.linalg.eig(matrix)
print(eignevalues)
print(eigenvectors)


[ 1.61168440e+01 -1.11684397e+00 -4.29954797e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [50]:
# 1.17 calculating dot products 
vector_a = np.array([1, 2, 3]) 
vector_b = np.array([4, 5, 6])
print(np.dot(vector_a, vector_b))
print(vector_a @ vector_b)

32
32


In [52]:
# 1.18 adding and subtracting matrices
matrix_a = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
matrix_b = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
print(np.add(matrix_a, matrix_b))
print(np.subtract(matrix_a, matrix_b))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [53]:
# 1.19 multiplying matrices 
matrix_a = np.array([[1, 1], 
                     [1, 2]])
matrix_b = np.array([[1, 3], 
                     [1, 2]])
print(np.dot(matrix_a, matrix_b))


[[2 5]
 [3 7]]


In [54]:
# 1.20 inverting a matrix 
matrix = np.array([[1, 4], 
                   [2, 5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [56]:
# 1.21 genertaing random values 
np.random.seed(0)
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])